import { Order } from './types';
import { addDays, subDays } from 'date-fns';

export const mockOrders: Order[] = [
  {
    id: 'ORD-1001',
    customerName: 'Tech Solutions SA',
    orderDate: subDays(new Date(), 10),
    deliveryDeadline: addDays(new Date(), 2),
    status: 'pending',
    items: 'Laptops x10, Monitors x20',
    priority: 'high',
    tmsStatus: 'En Tránsito',
  },
  {
    id: 'ORD-1002',
    customerName: 'Global Logistics Corp',
    orderDate: subDays(new Date(), 15),
    deliveryDeadline: subDays(new Date(), 1),
    actualDeliveryDate: subDays(new Date(), 2),
    status: 'delivered',
    items: 'Pallets x5',
    priority: 'medium',
    tmsStatus: 'Finalizado',
  },
  {
    id: 'ORD-1003',
    customerName: 'EduGroup LLC',
    orderDate: subDays(new Date(), 5),
    deliveryDeadline: addDays(new Date(), 1),
    status: 'pending',
    items: 'Tablets x50',
    priority: 'high',
    tmsStatus: 'Asignado',
  },
  {
    id: 'ORD-1004',
    customerName: 'Retail Giant Inc',
    orderDate: subDays(new Date(), 20),
    deliveryDeadline: subDays(new Date(), 5),
    actualDeliveryDate: subDays(new Date(), 2),
    status: 'delivered',
    items: 'Mixed electronics',
    priority: 'low',
    tmsStatus: 'Finalizado',
  },
  {
    id: 'ORD-1005',
    customerName: 'HealthPlus Co',
    orderDate: subDays(new Date(), 8),
    deliveryDeadline: addDays(new Date(), 12),
    status: 'pending',
    items: 'Medical Supplies',
    priority: 'medium',
    tmsStatus: 'En Almacén',
  },
  {
    id: 'ORD-1006',
    customerName: 'Innovatech',
    orderDate: subDays(new Date(), 2),
    deliveryDeadline: addDays(new Date(), 4),
    status: 'pending',
    items: 'Servers x2',
    priority: 'high',
    tmsStatus: 'Preparación',
  },
  {
    id: 'ORD-1007',
    customerName: 'Alpha Systems',
    orderDate: subDays(new Date(), 12),
    deliveryDeadline: subDays(new Date(), 2),
    status: 'pending',
    items: 'Cables and Wiring',
    priority: 'high',
    tmsStatus: 'Atrasado',
  }
];
