import { Order } from './types';
import { addDays, subDays } from 'date-fns';

export const mockOrders: Order[] = [
  {
    id: 'ORD-1001',
    uniqueId: 'ORD-1001',
    customerName: 'Tech Solutions SA',
    createdAt: subDays(new Date(), 10),
    deliveryDeadline: addDays(new Date(), 2),
    status: 'pending',
    items: 'Laptops x10, Monitors x20',
    priority: 'high',
    tmsStatus: 'En Tránsito',
    recipient: 'Juan Pérez',
    location: 'Buenos Aires',
    packages: 5,
    weight: 25.5,
    shift: 'Mañana',
  },
  {
    id: 'ORD-1002',
    uniqueId: 'ORD-1002',
    customerName: 'Global Logistics Corp',
    createdAt: subDays(new Date(), 15),
    deliveryDeadline: subDays(new Date(), 1),
    actualDeliveryDate: subDays(new Date(), 2),
    status: 'delivered',
    items: 'Pallets x5',
    priority: 'medium',
    tmsStatus: 'Finalizado',
    recipient: 'María García',
    location: 'Córdoba',
    packages: 12,
    weight: 450.0,
    shift: 'Tarde',
  },
  {
    id: 'ORD-1003',
    uniqueId: 'ORD-1003',
    customerName: 'EduGroup LLC',
    createdAt: subDays(new Date(), 5),
    deliveryDeadline: addDays(new Date(), 1),
    status: 'pending',
    items: 'Tablets x50',
    priority: 'high',
    tmsStatus: 'Asignado',
    recipient: 'Carlos López',
    location: 'Rosario',
    packages: 3,
    weight: 15.2,
    shift: 'Mañana',
  },
  {
    id: 'ORD-1004',
    uniqueId: 'ORD-1004',
    customerName: 'Retail Giant Inc',
    createdAt: subDays(new Date(), 20),
    deliveryDeadline: subDays(new Date(), 5),
    actualDeliveryDate: subDays(new Date(), 2),
    status: 'delivered',
    items: 'Mixed electronics',
    priority: 'low',
    tmsStatus: 'Finalizado',
    recipient: 'Ana Martínez',
    location: 'Mendoza',
    packages: 20,
    weight: 120.5,
    shift: 'Noche',
  },
  {
    id: 'ORD-1005',
    uniqueId: 'ORD-1005',
    customerName: 'HealthPlus Co',
    createdAt: subDays(new Date(), 8),
    deliveryDeadline: addDays(new Date(), 12),
    status: 'pending',
    items: 'Medical Supplies',
    priority: 'medium',
    tmsStatus: 'En Almacén',
    recipient: 'Roberto Sánchez',
    location: 'La Plata',
    packages: 8,
    weight: 35.8,
    shift: 'Tarde',
  },
  {
    id: 'ORD-1006',
    uniqueId: 'ORD-1006',
    customerName: 'Innovatech',
    createdAt: subDays(new Date(), 2),
    deliveryDeadline: addDays(new Date(), 4),
    status: 'pending',
    items: 'Servers x2',
    priority: 'high',
    tmsStatus: 'Preparación',
    recipient: 'Laura Torres',
    location: 'Mar del Plata',
    packages: 2,
    weight: 85.0,
    shift: 'Mañana',
  },
  {
    id: 'ORD-1007',
    uniqueId: 'ORD-1007',
    customerName: 'Alpha Systems',
    createdAt: subDays(new Date(), 12),
    deliveryDeadline: subDays(new Date(), 2),
    status: 'pending',
    items: 'Cables and Wiring',
    priority: 'high',
    tmsStatus: 'Atrasado',
    recipient: 'Diego Ramírez',
    location: 'Salta',
    packages: 1,
    weight: 10.0,
    shift: 'Tarde',
  }
];
